# Generated by Django 3.2.2 on 2021-05-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='', verbose_name='fotos/%d,%m,%Y'),
        ),
    ]
